server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 3
    eviction-interval-timer-in-ms: 2000
